name: "Hello world workflow"

on:
    push:
        branches:
            - master
            - production
            
jobs:
    hello_world:
        runs-on: windows-latest

        steps:
            - name: print hello world
              run: echo "Hello world"