name: "Multi event pipeline / workflow"

on:
    push:
        branches:
            - master
            - test
    
    pull_request:
        branches:
            -master
        types:
            - closed
            - opened
    workflow_dispatch:

jobs:
    on-push:
        if: ${{ github.event_name == 'push' }}
        runs-on: windows-latest
        steps:
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
    
    on-pull-request:
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: windows-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    
    on-pull-request-closed:
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
        runs-on: windows-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"

    on-pull-request-opened:
        if: ${{ github.event_name == 'pull-request' && github.event.action == 'opened' }}
        runs-on: windows-latest
        steps:
            - name: "Running on pull request opened"
              run: echo "Running on pull request opened""

            

